"""new init

Revision ID: 46222d4c823c
Revises: 
Create Date: 2023-09-07 21:15:29.941455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46222d4c823c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='CONFIRMED_STATUS', nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('entry')
    # ### end Alembic commands ###
