"""Posts

Revision ID: 60048ef0a543
Revises: 005663d5b6a1
Create Date: 2023-09-20 16:37:44.362496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60048ef0a543'
down_revision = '005663d5b6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titul', sa.String(length=20), nullable=False),
    sa.Column('postText', sa.String(length=300), nullable=False),
    sa.Column('videoUrl', sa.String(length=100), nullable=True),
    sa.Column('createData', sa.DateTime(), nullable=False),
    sa.Column('updateData', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
